// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjxevsqonqchzxiodxni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqeGV2c3FvbnFjaHp4aW9keG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODg5MDksImV4cCI6MjA3MzQ2NDkwOX0.ikQ4fbloQXdLpCBXFV7bBivCuSfPl6tWRoDN44SYlpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});